version: "3.8"

services:
  repo:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgres/data
    networks:
      - repo

volumes:
  postgres-data:
networks:
  repo: